name: petziee
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.0.0
  firebase_auth: ^1.0.3
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.0.3
  firebase_core: ^1.0.3
  firebase_database: ^6.1.2
  archive: ^3.1.2
  image: ^3.0.2
  #  animator: ^3.0.0
  image_picker: ^0.7.4
  #  google_sign_in: ^5.0.2
  #  timeago: ^3.0.2
  cached_network_image:
  geolocator: ^7.0.2
  uuid: ^3.0.4
  #  extended_text_field: ^7.0.0
  #  flutter_svg: ^0.22.0
  intl: ^0.17.0
  google_maps_flutter: ^2.0.3
  geocoding: ^2.0.0
  location: ^4.1.1
  #  flutter_google_places: ^0.3.0
  http: ^0.13.1
  #  flutter_slidable: ^0.6.0
  swipeable: ^1.1.0
  scrollable_positioned_list: ^0.1.8
  file_picker: ^3.0.1
  mime: ^1.0.0
  flutter_colorpicker: ^0.4.0
  video_trimmer: ^0.4.0
  video_player: ^2.1.1
  google_fonts: ^2.0.0
  cloud_functions: ^1.0.5




  native_device_orientation: ^1.0.0
  lottie: ^1.0.1
  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^2.0.0
  dashed_container: ^1.0.1
  preload_page_view: ^0.1.6
  camera: ^0.8.1
  path_provider: ^2.0.1
  local_image_provider: ^4.0.0-nullsafety
  permission_handler: ^6.1.1
  shared_preferences: ^2.0.5
  flutter_uploader: ^3.0.0-beta.1
  flutter_local_notifications: ^5.0.0+3
  flutter_ffmpeg: ^0.4.0
  video_thumbnail: ^0.3.3
  #  workmanager: ^0.4.0
  enum_to_string: ^2.0.1
  rxdart: ^0.26.0
  extended_image: ^4.0.1
  image_cropper: ^1.4.0
  #  pull_to_refresh: ^2.0.0
  photo_view: ^0.11.1
  chewie: ^1.0.0
  #  flutter_blurhash: ^0.6.0
  #  blurhash_dart: ^1.0.2
  tapioca: ^1.0.2+1
  custom_info_window: ^1.0.1
  clippy_flutter: ^1.1.1
  url_launcher: ^6.0.6
  neumorphic: ^0.4.0
  provider: ^5.0.0
  flutter_native_timezone: ^2.0.0
  workmanager: ^0.4.1
  flutter_countdown_timer: ^4.1.0












  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_analytics: ^8.0.2

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_native_splash: ^1.2.0




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - json_files/
    - assets/pets/
    - assets/map_styles/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.

  color: "#000000"

  #  background_image: "assets/home.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file.
  image: assets/splash.png

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: center

  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

  # To enable support for Android 12, set the following parameter to true.  Defaults to false.
#  android12: true